# Generated by Django 5.2 on 2025-10-19 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_cliente_tipo_cliente'),
        ('dashboard', '0001_initial'),
        ('lotes', '0006_alter_lote_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ID_Ventas', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Venta', models.DateTimeField(auto_now_add=True)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('IVA', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Estado_Pago', models.CharField(choices=[('completo', 'Completo'), ('pendiente', 'Pendiente')], default='completo', max_length=10)),
                ('Metodo_Pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('pago_movil', 'Pago Móvil')], default='efectivo', max_length=15)),
                ('Tipo_Venta', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('Cedula', models.ForeignKey(db_column='Cedula', on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('ID_Detalle', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(default=1)),
                ('Precio_Unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Subtotal_Detalle', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ID_Tasa', models.ForeignKey(db_column='ID_Tasa', on_delete=django.db.models.deletion.CASCADE, to='dashboard.tasacambiaria')),
                ('ID_lote', models.ForeignKey(db_column='ID_lote', on_delete=django.db.models.deletion.CASCADE, to='lotes.lote')),
                ('ID_Ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalle_venta',
            },
        ),
    ]
