# Generated by Django 5.2 on 2025-10-20 00:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='Abono_Inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='Saldo_Pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='Cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Estado_Pago',
            field=models.CharField(choices=[('completo', 'Completo'), ('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Metodo_Pago',
            field=models.CharField(blank=True, choices=[('efectivo_bs', 'Efectivo Bs'), ('efectivo_usd', 'Efectivo $'), ('transferencia', 'Transferencia'), ('pago_movil', 'Pago Móvil'), ('tarjeta', 'Tarjeta'), ('punto_venta', 'Punto de Venta')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('ID_Pago', models.AutoField(primary_key=True, serialize=False)),
                ('Metodo_Pago', models.CharField(choices=[('efectivo_bs', 'Efectivo Bs'), ('efectivo_usd', 'Efectivo $'), ('transferencia', 'Transferencia'), ('pago_movil', 'Pago Móvil'), ('tarjeta', 'Tarjeta'), ('punto_venta', 'Punto de Venta')], max_length=15)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Tasa_Cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Monto_Bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('Fecha_Pago', models.DateTimeField(auto_now_add=True)),
                ('ID_Ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
    ]
