# Generated by Django 5.2 on 2025-10-20 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_abono_inicial_venta_saldo_pendiente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='Metodo_Pago',
        ),
        migrations.AlterField(
            model_name='pago',
            name='Fecha_Pago',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Fecha_Venta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
