# Generated by Django 5.2 on 2025-10-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_venta_metodo_pago_alter_pago_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
