# Generated by Django 5.2 on 2025-11-28 01:48

import ventas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_venta_anulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='Fecha_Pago',
            field=models.DateTimeField(default=ventas.models.Pago.default_fecha_venezuela),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Fecha_Venta',
            field=models.DateTimeField(default=ventas.models.Venta.default_fecha_venezuela),
        ),
    ]
