# Generated by Django 5.2 on 2026-01-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_pago_fecha_pago_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='IVA_USD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='Saldo_Pendiente_USD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='Subtotal_USD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='Tasa_Venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='Total_USD',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
