# Generated by Django 5.2 on 2026-01-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='account_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
