# Generated by Django 5.2 on 2026-01-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_account_locked_usuario_failed_login_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_backup', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('size_mb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_recipient', models.EmailField(max_length=254)),
                ('is_automatic', models.BooleanField(default=True)),
                ('is_pending', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historial de Backup',
                'verbose_name_plural': 'Historial de Backups',
                'ordering': ['-fecha_backup'],
            },
        ),
    ]
