# Generated by Django 5.2 on 2025-12-03 06:24

import cuentas_pendientes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_alter_cliente_direccion'),
        ('ventas', '0006_alter_pago_fecha_pago_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('ID_Abono', models.AutoField(primary_key=True, serialize=False)),
                ('Monto_Abono', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Metodo_Pago', models.CharField(choices=[('efectivo_bs', 'Efectivo Bs'), ('efectivo_usd', 'Efectivo $'), ('transferencia', 'Transferencia'), ('pago_movil', 'Pago Móvil'), ('tarjeta', 'Tarjeta')], max_length=15)),
                ('Tasa_Cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Monto_Abono_Bs', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('Observaciones', models.TextField(blank=True, null=True)),
                ('Fecha_Abono', models.DateTimeField(default=cuentas_pendientes.models.Abono.default_fecha_venezuela)),
                ('Saldo_Anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Saldo_Despues', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Registrado_Por', models.CharField(blank=True, max_length=100, null=True)),
                ('anulado', models.BooleanField(default=False)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='clientes.cliente')),
                ('ID_Ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'db_table': 'abonos',
                'ordering': ['-Fecha_Abono'],
            },
        ),
    ]
