# Generated by Django 5.2 on 2025-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('alimentos', 'Alimentos'), ('bebidas', 'Bebidas'), ('miscelaneos', 'Miscelaneos'), ('medicamentos', 'Medicamentos'), ('otros', 'Otros')], max_length=50),
        ),
    ]
