# Generated by Django 5.2 on 2025-10-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='nombre_pro',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='ref',
            new_name='precio_venta',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='stock_minimo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='valor',
        ),
        migrations.AddField(
            model_name='producto',
            name='ID_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
