# Generated by Django 5.2 on 2025-10-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_options_producto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('agotado', 'Agotado')], default='activo', help_text='Los productos inactivos no podrán recibir lotes', max_length=10),
        ),
    ]
