# Generated by Django 5.2 on 2025-11-04 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patología',
                'verbose_name_plural': 'Patologías',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='sujeto_iva',
            field=models.CharField(choices=[('si', 'Sujeto a IVA'), ('no', 'No Sujeto a IVA')], default='si', max_length=2, verbose_name='Sujeto a IVA'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Máximo 15 caracteres (letras, números y espacios)', max_length=15, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_pro',
            field=models.CharField(max_length=100, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.categoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='patologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.patologia', verbose_name='Patología'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('nombre_pro',), name='unique_nombre_producto', violation_error_message='Ya existe un producto activo con este nombre'),
        ),
    ]
