# Generated by Django 5.2 on 2025-11-04 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_categoria_patologia_producto_sujeto_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patologia',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_pro',
            field=models.CharField(help_text='Solo letras y números (máximo 100 caracteres)', max_length=100, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(9999.99)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(default=3, help_text='Máximo 15 caracteres (letras, números y espacios)', max_length=15, verbose_name='Ubicación'),
            preserve_default=False,
        ),
    ]
