# Generated by Django 5.2 on 2025-11-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_categoria_nombre_alter_patologia_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_pro',
            field=models.CharField(help_text='Solo letras y números (máximo 30 caracteres)', max_length=30, verbose_name='Nombre del Producto'),
        ),
    ]
