# Generated by Django 5.2 on 2025-11-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_producto_nombre_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='serial',
            field=models.CharField(default=' ', help_text='Máximo 25 caracteres, solo números', max_length=25, unique=True, verbose_name='Serial'),
        ),
    ]
