# Generated by Django 5.2 on 2026-01-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_pro',
            field=models.CharField(help_text='Solo letras, números y espacios (máximo 30 caracteres)', max_length=30, verbose_name='Nombre del Producto'),
        ),
    ]
