# Generated by Django 5.2 on 2026-01-07 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99999999.99)]),
        ),
    ]
