# Generated by Django 5.2 on 2025-10-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_tipo_cliente_alter_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('particular', 'Particular'), ('mayorista', 'Mayorista')], default='particular', max_length=10),
        ),
    ]
