# Generated by Django 5.2 on 2025-12-20 21:20

import cierre_caja.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('ID_Cierre', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Cierre', models.DateField(unique=True)),
                ('Fecha_Creacion', models.DateTimeField(default=cierre_caja.models.CierreCaja.default_fecha_venezuela)),
                ('Sistema_Efectivo_Bs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Sistema_Efectivo_USD', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Sistema_Transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Sistema_Pago_Movil', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Sistema_Tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Sistema_Punto_Venta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Real_Efectivo_Bs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Real_Efectivo_USD', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Real_Transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Real_Pago_Movil', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Real_Tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Real_Punto_Venta', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Total_Sistema', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Total_Real', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Diferencia_Total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Notas', models.TextField(blank=True, null=True)),
                ('Cerrado', models.BooleanField(default=False)),
                ('Usuario', models.ForeignKey(db_column='Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'db_table': 'cierre_caja',
                'ordering': ['-Fecha_Cierre'],
            },
        ),
    ]
