# Generated by Django 5.2 on 2025-10-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
        ('productos', '0005_alter_producto_options_producto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='costo_lote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lote',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
    ]
