# Generated by Django 5.2 on 2025-10-08 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_lote_costo_lote_alter_lote_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='fecha_recibimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
