# Generated by Django 5.2 on 2025-10-08 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_lote_fecha_recibimiento'),
        ('productos', '0005_alter_producto_options_producto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='productos.producto'),
        ),
    ]
