# Generated by Django 5.2 on 2025-10-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0005_rename_costo_lote_lote_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='proveedor',
            field=models.CharField(default='Sin proveedor', max_length=100, verbose_name='Proveedor'),
        ),
    ]
