# Generated by Django 5.2 on 2025-10-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0006_alter_lote_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='proveedor',
            field=models.CharField(default='', max_length=100, verbose_name='Proveedor'),
        ),
    ]
