# Generated by Django 5.2 on 2025-11-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0007_alter_lote_proveedor'),
        ('productos', '0009_alter_producto_nombre_pro'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('id_producto', 'fecha_recibimiento', 'fecha_vencimiento', 'proveedor'), name='unique_lote_producto_fechas_proveedor'),
        ),
    ]
