# Generated by Django 5.2 on 2025-11-25 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0009_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.proveedor', verbose_name='Proveedor'),
        ),
    ]
