# Generated by Django 5.2 on 2025-11-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0010_alter_lote_proveedor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lote',
            name='unique_lote_producto_fechas_proveedor',
        ),
    ]
